### ISSUE TITLE
大佬有没有phpstorm插件开发相关的资料

### ISSUE THREAD

**Issue by 327100395** [fw6669998/php-doc#1]
大佬有没有phpstorm插件开发相关的资料

**Comment by fw6669998** [comment]
开发文档: http://www.jetbrains.org/intellij/sdk/docs/welcome.html
搜索引擎: google	//很多东西真的要google才搜的到
源码及示例: https://github.com/JetBrains/intellij-community
入门参考: https://cloud.tencent.com/developer/article/1348741
