### ISSUE TITLE
不能正常使用，所有的关键字提示都失效了

### ISSUE THREAD

**Issue by oracleKing** [fw6669998/php-doc#10]
你好，非常喜欢这款插件，但是我的phpstorm 不能正常使用
![image](https://user-images.githubusercontent.com/14267316/105018412-ea1c4600-5a7f-11eb-81ce-8d2e5eee2fbf.png)
![image](https://user-images.githubusercontent.com/14267316/105018456-f902f880-5a7f-11eb-9726-be0b72273ec0.png)
我尝试关闭了其他插件都不行，插件也没有报错

**Comment by oracleKing** [comment]
![image](https://user-images.githubusercontent.com/14267316/105019586-37e57e00-5a81-11eb-9287-c31f1863ae41.png)
zheg这个插件是能正常使用的

**Comment by fw6669998** [comment]
不确定有没有用,你可以试下

**Comment by fw6669998** [comment]
不确定有没有用, 你可以试下,
选择 File菜单下的 Invalid Caches / Restart选项

**Comment by oracleKing** [comment]
> 不确定有没有用，你可以试下，
> 选择File菜单下的无效的缓存/重新启动选项
尝试过了依然不行，不过没关系我可以用你的另外一个插件 php document ,它也挺好用的，下次我尝试卸载重装试试

**Comment by oldqing** [comment]
![image](https://user-images.githubusercontent.com/43989954/112802891-4ebdd780-90a5-11eb-8ae0-0e2b23ecde76.png)
![image](https://user-images.githubusercontent.com/43989954/112802933-59786c80-90a5-11eb-829e-66d8512eeef9.png)
同意的问题,尝试过Invalid Caches / Restart 但问题没有解决,关闭插件后恢复正常 phpstrom2020.3.3

**Comment by fw6669998** [comment]
可能是重新建立索引的进程还没跑完, 要等右下角的进度框跑完
![image](https://user-images.githubusercontent.com/22911360/113122106-e2c6a500-9245-11eb-8bfd-ccdd465b05c6.png)


> ![image](https://user-images.githubusercontent.com/43989954/112802891-4ebdd780-90a5-11eb-8ae0-0e2b23ecde76.png)
> ![image](https://user-images.githubusercontent.com/43989954/112802933-59786c80-90a5-11eb-829e-66d8512eeef9.png)
> 同意的问题,尝试过Invalid Caches / Restart 但问题没有解决,关闭插件后恢复正常 phpstrom2020.3.3

**Comment by oldqing** [comment]
@

> 可能是重新建立索引的进程还没跑完, 要等右下角的进度框跑完
> ![image](https://user-images.githubusercontent.com/22911360/113122106-e2c6a500-9245-11eb-8bfd-ccdd465b05c6.png)
> 
> > ![image](https://user-images.githubusercontent.com/43989954/112802891-4ebdd780-90a5-11eb-8ae0-0e2b23ecde76.png)
> > ![image](https://user-images.githubusercontent.com/43989954/112802933-59786c80-90a5-11eb-829e-66d8512eeef9.png)
> > 同意的问题,尝试过Invalid Caches / Restart 但问题没有解决,关闭插件后恢复正常 phpstrom2020.3.3

进程跑完了也没效果, Invalid Caches / Restart也没效果 
我的插件如下： 应该也不是插件插件冲突 我也尝试过php Document 也是无效的，我是从2020.1 升级后 产生的问题，现在怀疑是phpstrom的版本兼容问题。 
![image](https://user-images.githubusercontent.com/43989954/113408217-88624b80-93e1-11eb-9438-78b73e57c3cd.png)

**Comment by oracleKing** [comment]
今天又尝试了一下，毕竟升为2021了， 发现清除缓存重启后好了。暂不知具体原因是啥
![image](https://user-images.githubusercontent.com/14267316/120303884-d9b78a00-c301-11eb-9ba7-08ac3c2e8ef7.png)
![image](https://user-images.githubusercontent.com/14267316/120303968-ec31c380-c301-11eb-8202-21ee25bddbc4.png)
![image](https://user-images.githubusercontent.com/14267316/120304048-ffdd2a00-c301-11eb-9520-a516ecc06aca.png)
