### ISSUE TITLE
PDO::exec

### ISSUE THREAD

**Issue by ipuppet** [fw6669998/php-doc#11]
`PDO::exec` 可能被识别成了 `exec()` 函数了  
这不是php基本函数，我应该如何排除这个错误识别？
phpstorm里一直显示我这用了void函数返回值。。。/(ㄒoㄒ)/~~
![image](https://user-images.githubusercontent.com/37722993/128587775-feb88475-23d2-4b20-af16-932bb30a663d.png)
![image](https://user-images.githubusercontent.com/37722993/128587809-c9158de7-c2dc-4fea-b119-bb56ba03fc6f.png)

**Comment by fw6669998** [comment]
![image](https://user-images.githubusercontent.com/22911360/152549910-b561bd00-2987-4f5d-a6ef-ede29960b7be.png)
修改文档时的问题, 删除文档这2行就正常了
