### ISSUE TITLE
请问mac版 怎么使用

### ISSUE THREAD

**Issue by Bigweixi** [fw6669998/php-doc#6]
mac版按了没反应

**Comment by fw6669998** [comment]
如果安装成功,但按ctrl+q快捷键没有反应,打开File->setting->keymap 搜索quick document,查看你的快捷键是什么,如果没有快捷键,可以自己设置

**Comment by Bigweixi** [comment]
好的谢谢大佬------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;fw6669998&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月15日(星期天) 中午12:22
收件人:&nbsp;&quot;fw6669998/php-doc&quot;<php-doc@noreply.github.com&gt;;
抄送:&nbsp;&quot;name_peng&quot;<1925186789@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fw6669998/php-doc] 请问mac版 怎么使用 (#6)
