### ISSUE TITLE
sizeof 函数签名提示错误

### ISSUE THREAD

**Issue by zvrh** [fw6669998/php-doc#7]
`sizeof` 是`count`的别名，签名应该是：`function sizeof($var, $mode = COUNT_NORMAL) int` 但被错误的标记为了 `function sizeof($var, $mode) int`

参考：
https://www.php.net/manual/en/function.sizeof.php
https://www.php.net/manual/en/function.count.php

**Comment by fw6669998** [comment]
更新1.2版本,修改了
